name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1

jobs:
  build-linux-clangdwarf:
    name: Linux CLANGDWARF
    runs-on: ubuntu-latest
    env:
      TOOLCHAINS: CLANGDWARF
    steps:
      - uses: actions/checkout@v4

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: ./build_duet.tool
        run: docker compose run build-duet

      - name: ./build_oc.tool
        run: docker compose run build-oc

      - name: Upload o Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux CLANGDWARF Artifacts
          path: Binaries/*.zip
